-- ============================================================
-- Seeder: Bienes de Equipo 2025 - Cultura del Agua
-- Programa E005 Capacitacion Ambiental y Desarrollo Sustentable
-- Fuente: FormatoparaaltadebienesEQUIPO.csv
-- Fecha generacion: 2026-03-09  (v2: FROM DUAL pattern)
-- ============================================================

USE sistema_ceaa;
SET NAMES utf8mb4;

-- Seccion 1: Sistemas de Proyeccion Fulldome (3 registros)

INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT '364791','SISTEMA DE PROYECCION FULLDOME FISHEYE PLUS INCLUYE: PROYECTOR DE 6,000 LUMENES LASER FULL HD-BLU RAY MULTIMEDIA 4K-LENTE FISHEYE',2,4,'FEDERAL','COMPRA',157528.00,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'PROYECTOR: CHRISTIE / LENTE: COSMOTEC / BLURAY: SONY','PROYECTOR: DHD630-GS / LENTE: FISHEYE / BLURAY: N/A','PROYECTOR: FWH1942002 / LENTE: 243656 / BLURAY: BON562','PROYECTOR: BLANCO / LENTE: NEGRO / BLURAY: N/A','PROYECTOR: PLASTICO / LENTE: N/A / BLURAY: N/A','Comision Estatal del Agua y Alcantarillado' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='364791');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT '364792','SISTEMA DE PROYECCION FULLDOME FISHEYE PLUS INCLUYE: PROYECTOR DE 6,000 LUMENES LASER FULL HD-BLU RAY MULTIMEDIA 4K-LENTE FISHEYE',2,4,'FEDERAL','COMPRA',157528.00,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'PROYECTOR: CHRISTIE / LENTE: COSMOTEC / BLURAY: SONY','PROYECTOR: DHD630-GS / LENTE: FISHEYE / BLURAY: N/A','PROYECTOR: FWH1812042 / LENTE: 243657 / BLURAY: BON684','PROYECTOR: BLANCO / LENTE: NEGRO / BLURAY: N/A','PROYECTOR: PLASTICO / LENTE: N/A / BLURAY: N/A','Comision Estatal del Agua y Alcantarillado' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='364792');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT '364793','SISTEMA DE PROYECCION FULLDOME FISHEYE PLUS INCLUYE: PROYECTOR DE 6,000 LUMENES LASER FULL HD-BLU RAY MULTIMEDIA 4K-LENTE FISHEYE',2,4,'FEDERAL','COMPRA',157528.00,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'PROYECTOR: CHRISTIE / LENTE: COSMOTEC / BLURAY: SONY','PROYECTOR: DHD630-GS / LENTE: FISHEYE / BLURAY: N/A','PROYECTOR: SKU 670667 / LENTE: 243658 / BLURAY: BON613','PROYECTOR: BLANCO / LENTE: NEGRO / BLURAY: N/A','PROYECTOR: PLASTICO / LENTE: N/A / BLURAY: N/A','Comision Nacional del Agua' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='364793');

-- Seccion 2: Gafas de Realidad Virtual 3D (42 registros)

INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-01','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Acatlan, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-01');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-02','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua, Alcantarillado y Saneamiento de Actopan, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-02');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-03','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Agua Blanca de Iturbide, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-03');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-04','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua Potable, Alcantarillado y Saneamiento de Atitalaquia, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-04');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-05','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Atlapexco' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-05');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-06','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Eloxochitlan' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-06');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-07','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Epazoyucan' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-07');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-08','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua del Municipio de Huasca, Hgo.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-08');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-09','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Huazalingo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-09');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-10','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Huehuetla' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-10');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-11','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua Potable, Alcantarillado y Saneamiento de Huejutla, Hgo.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-11');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-12','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Huejutla de Reyes (Universidad Politecnica de Huejutla)' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-12');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-13','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Juarez Hidalgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-13');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-14','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de La Mision' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-14');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-15','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Lolotla' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-15');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-16','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Metepec' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-16');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-17','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Mineral del Monte' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-17');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-18','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua y Alcantarillado del Municipio de Mixquiahuala de Juarez, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-18');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-19','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Molango de Escamilla' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-19');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-20','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Nicolas Flores' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-20');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-21','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Zempoala Acueducto del Padre Tembleque' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-21');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-22','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Pisaflores' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-22');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-23','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua y Alcantarillado del Municipio de Progreso de Obregon, Hgo.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-23');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-24','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de San Bartolo Tutotepec' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-24');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-25','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de San Felipe Orizatlan' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-25');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-26','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua Potable, Alcantarillado y Saneamiento de Santiago de Anaya, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-26');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-27','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua, Alcantarillado y Saneamiento de Santiago Tulantepec de Lugo Guerrero, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-27');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-28','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Singuilucan' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-28');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-29','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tasquillo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-29');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-30','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tenango de Doria' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-30');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-31','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tepeapulco' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-31');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-32','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua y Alcantarillado del Municipio de Tepeji del Rio Ocampo, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-32');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-33','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tianguistengo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-33');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-34','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Comision de Agua y Alcantarillado del Municipio de Tizayuca, Hgo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-34');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-35','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tlanalapa' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-35');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-36','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tlanchinol' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-36');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-37','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tolcayuca' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-37');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-38','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Tulancingo de Bravo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-38');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-39','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Xochiatipan' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-39');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-40','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Yahualica' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-40');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-41','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Zapotlan de Juarez' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-41');
INSERT INTO recursos (clave,nombre,categoria_id,unidad_id,tipo_fuente,fuente,costo_unitario,cantidad_total,cantidad_disponible,estado_bien,fecha_alta,accion,concepto,anio_fortalecimiento,marca,modelo,numero_serie,color,material,beneficiario)
SELECT 'GAFAS 3D-25-42','GAFAS DE REALIDAD VIRTUAL 3D PARA IPHONE SAMSUNG XIAOMI SMARTPHONES FOV 120 GRADOS VR STEREO BOX.',2,4,'FEDERAL','COMPRA',1506.84,1,1,'bueno','2025-01-01','Programa E005 Capacitacion Ambiental y Desarrollo Sustentable en relacion a las acciones de Cultura del Agua (Material Didactico Adquirido de Cultura del Agua)','Distribucion de Material Didactico Adquirido de Cultura del Agua 2025 (Recurso Federal)',2025,'Sin Marca','Sin modelo','Sin numero de serie','Negro','Plastico','Presidencia Municipal de Zempoala' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM recursos WHERE clave='GAFAS 3D-25-42');

-- Verificacion final
SELECT COUNT(*) AS registros_insertados FROM recursos WHERE tipo_fuente = 'FEDERAL' AND anio_fortalecimiento = 2025;